apiVersion: v1
kind: LimitRange
metadata:
  name: default-resource-limits
  namespace: i-ikromov
spec:
  limits:
    - type: Container
      default:
        cpu: "200m"
      defaultRequest:
        cpu: "100m"
      min:
        cpu: "50m"
      max:
        cpu: "1"
